name: Lint

on:
  push:
    branches-ignore:
      - production
      - stating
    paths:
      - '**/*.tf'

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate terraform configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        
      - name: Harden Runner
        uses: step-security/harden-runner@v2.10.1
        with:
          egress-policy: audit

      - name: terraform validate
        uses: dflook/terraform-validate@v1.44.0
        with:
          path: workload/terraform/jamfpro

  fmt-check:
    runs-on: ubuntu-latest
    name: Check formatting of terraform files
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1.44.0
        with:
          path: workload/terraform/jamfpro
      
      - name: Wrong formatting found
        if: ${{ failure() && steps.fmt-check.outputs.failure-reason == 'fmt-check' }}
        run: echo "formatting check failed"